### ISSUE TITLE
Failed search: Rel: can't make var/lib/ci-search/bugs/... relative to /var/lib/ci-search/

### ISSUE THREAD

**Issue by wking** [openshift/ci-search#41]
```console
$ curl 'https://search.svc.ci.openshift.org/search?name=whatever&search=promQL+query&type=build-log'
Failed search: Rel: can't make var/lib/ci-search/bugs/bug-1790825 relative to /var/lib/ci-search/
{}
```

Clearing either `name` or `type` avoids the issue.  No idea why CI-search cares about bug rel paths for `type=build-log` queries.

**Comment by smarterclayton** [comment]
This is almost certainly a bug either in ripgrep or more likely our parsing we are off by one in our read of the contents.
