### ISSUE TITLE
Number of runs count off, resulting in "200% of failures match" and similar

### ISSUE THREAD

**Issue by wking** [openshift/ci-search#75]
For [example][1]:

![Screenshot from 2020-04-27 12-56-04](https://user-images.githubusercontent.com/209920/80414891-967d2300-8886-11ea-92b0-dd8a226a4779.png)

[1]: https://search.svc.ci.openshift.org/?name=upgrade&search=promQL+query:+count_over_time.*ALERTS.*had+reported+incorrect+results

**Comment by smarterclayton** [comment]
Not a bug.

**Comment by smarterclayton** [comment]
Hover over the text.
