### ISSUE TITLE
Duplicate results for the same run in list view

### ISSUE THREAD

**Issue by JoelSpeed** [openshift/ci-search#94]
I ran a [query linked from sippy](https://search.ci.openshift.org/?maxAge=168h&context=1&type=bug%2Bjunit&name=4.7&maxMatches=5&maxBytes=20971520&groupBy=job&search=%5C%5Bsig-builds%5C%5D%5C%5BFeature%3ABuilds%5C%5D+build+can+reference+a+cluster+service++with+a+build+being+created+from+new-build+should+be+able+to+run+a+build+that+references+a+cluster+service) and while looking through the results, noticed that various runs are duplicated multiple times in the list, for example see screenshot below
![Screenshot 2020-11-26 at 14 12 17](https://user-images.githubusercontent.com/9232216/100360880-6d299e80-2ff1-11eb-91a2-220487ba4566.png)

From a UX perspective, this means that users manually have to deduplicate the list and scroll over the duplicate results. I would have expected the results to have been deduplicated before being rendered to the user. Is there some reason these aren't being deduplicated at present?

**Comment by smarterclayton** [comment]
That's the "5" field in the bottom right of the top search section.  We return 5 results by default from the same run, each one is a separate element

**Comment by JoelSpeed** [comment]
Ok, if that's intended behaviour then that's fine.

Is there some documentation for sippy that explains what the fields are on that second row?

Perhaps we could add tooltips to the boxes to explain what each one does, they all seem pretty cryptic to me at the moment
